app:
  name: "web_app"
  mode: "dev"
  port: ":8080"

log:
  level: "debug"
  infoFilename: "./info.log"
  errFilename: "./err.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "lz18738377974"
  dbname: "kob"
  max_idle_conns: 10
  max_open_conns: 30

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0